package fuzzy;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

public class FisiFuzzyCMeans extends JFrame {
    private JButton seleccionarButton;
    private JPanel panel;
    private JLabel fileName;
    private JSpinner spinner1;
    private JButton generarButton;

    private String filePath;
    private int clusterNumber = 1;


    public FisiFuzzyCMeans() {

        this.setTitle("FISI Fuzzy C-Means");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setSize(400, 200);
        this.add(this.panel);
        //fr.pack();
        this.setVisible(true);


        seleccionarButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                JFileChooser chooser = new JFileChooser();

                if (chooser.showOpenDialog(panel) == JFileChooser.APPROVE_OPTION) {

                    File selectedFile = chooser.getSelectedFile();
                    filePath = selectedFile.getPath();
                    fileName.setText(selectedFile.getName());
                }

            }
        });


        generarButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                boolean flag = true;
                clusterNumber = Integer.parseInt(spinner1.getValue().toString());


                if (filePath == null) {
                    JOptionPane.showMessageDialog(null, "Seleccionar archivo",
                            "Información", JOptionPane.INFORMATION_MESSAGE);
                    flag = false;
                }

                if (Integer.parseInt(spinner1.getValue().toString()) < 1) {
                    JOptionPane.showMessageDialog(null, "El número de clusters no debe de ser menor a 1",
                            "Información", JOptionPane.INFORMATION_MESSAGE);

                    flag = false;
                }

                if (flag) {
                    InicializadorFuzzy fuzzy = new InicializadorFuzzy(filePath, clusterNumber);
                    fuzzy.ejecutar();
                }
            }
        });
    }

    public static void main(String[] args) {

        new FisiFuzzyCMeans();


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        spinner1 = new JSpinner();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.ipadx = 10;
        gbc.insets = new Insets(0, 30, 0, 0);
        panel.add(spinner1, gbc);
        generarButton = new JButton();
        generarButton.setText("Generar");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.weighty = 0.2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipady = 10;
        gbc.insets = new Insets(0, 15, 0, 15);
        panel.add(generarButton, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Número de Clusters");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(0, 30, 0, 0);
        panel.add(label1, gbc);
        seleccionarButton = new JButton();
        seleccionarButton.setText("Seleccionar");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(0, 30, 0, 0);
        panel.add(seleccionarButton, gbc);
        fileName = new JLabel();
        fileName.setEnabled(true);
        fileName.setHorizontalAlignment(10);
        fileName.setText("");
        fileName.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panel.add(fileName, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Seleccionar archivo (.csv)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(0, 30, 0, 0);
        panel.add(label2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }


}
